baseURL = "https://blog.ztec.fr/"
title = "Chez Zed"
theme = "VHS"
enableRobotsTXT = true
disable_share = true
googleAnalytics = ""
enableGitInfo = true
staticDir = ["assets"]
timeout = "360s"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
enableEmoji = true
summaryLength = 10

[security.funcs]
getenv = ['^HUGO_', '^CI$', 'PP_TOKEN', 'PP_HOST']

[pagination]
    pagerSize = 99

[markup]
[markup.highlight]
style = 'vim'
noClasses = false
lineNumbersInTable = false
lineNos = true
anchorLineNos=true


[[menu.footer]]
    name = "Mentions légales"
    url = "https://www.ztec.fr/mentions-legales/"
    weight = 60

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    name = "Loïc Doubinine | Zed"
    site_slug = "blog"
    description = "Développeur, Architecte, DevOps et Site Reliability Engineer"
    images = ["graph-logo.jpg"]
    custom_css = ["css/blog.css"]
[languages]
    [languages.fr]
        languageName="Français"
    [languages.en]
        languageName="English"
        title = "Zed's place"
    [languages.en.params]
        description = "Developer, Architect, DevOps and Site Reliability Engineer"
    [[languages.en.menu.footer]]
        name = "Legals"
        url = "https://www.ztec.fr/en/legals/"
        weight = 60



[permalinks]
[permalinks.page]
  quick = "/:year/:month/:slug/"
  post = "/:year/:section/:slug/"
  loot = "/:year/:month/:day/:sections/:slug/"
  concert = "/:year/:month/:day/:sections[first]/:slug/"
[permalinks.term]
  sources = "/:sections/:slug/"
  artist = "/artists/:slug/"
  place = "/place/:slug/"


[taxonomies]
tag = 'tags'
source = 'sources'
resources = 'resources'
artist = 'artists'
place = 'places'
instrument = 'instruments'

