apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ztec-fr-ingress
spec:
  ingressClassName: haproxy-public
  rules:
  - host: blog.ztec.fr
    http:
      paths:
      - backend:
          service:
            name: blog
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - blog.ztec.fr
    secretName: star-ztec-fr-tls
