apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ztec-fr-ingress
spec:
  ingressClassName: haproxy-public
  tls:
    - hosts:
        - blog.ztec.fr
      secretName: star-ztec-fr-tls
  rules:
    - host: blog.ztec.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog
                port:
                  number: 80
